apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: guestbookphp
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  namespace: guestbookphp
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        deployment: guestbook
    spec:
      containers:
        - name: guestbook
          image: >-
            quay.io/markd/guestbook-php:ocp
          env:
            - name: PORT
              value: "8080"
            - name: REMOTE_DSN
              valueFrom:
                configMapKeyRef:
                  name: guestbook-config           # The ConfigMap this value comes from.
                  key: dsn                         # The key to fetch.
            - name: REMOTE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-user
            - name: REMOTE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database-password
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
