apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: guestbookphp
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: guestbookphp
spec: # specification for deployment resource
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for Pod
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for Pod
      containers:
      - name: mariadb
        image: quay.io/mariadb-foundation/mariadb-devel
        ports:
        - containerPort: 3306 #default one
        env:
        - name: MARIADB_RANDOM_ROOT_PASSWORD
          value: "1"
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb                        # The ConfigMap this value comes from.
              key: database-name                   # The key to fetch.
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password